### ISSUE TITLE
crypto: use flow-go/crypto instead of internal

### ISSUE THREAD

**Issue by tarakby** [onflow/flow-go-sdk#113]
### Context

The SDK used its own copy of the crypto code because it got open-sourced while flow-go was still private. That shouldn't be the case anymore as flow-go became public.

### Definition of done

Delete flow-go-sdk/crytpo/internal and use onflow/flow-go/crypto instead.

**Comment by bjartek** [comment]
It looks like the crypto/internal package is done now, why was this reopened?

**Comment by tarakby** [comment]
It's a mistake, thanks for pointing out!
