### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by Randy1Burrell** [onflow/flow-go-sdk#121]
**Is your issue related to a problem? Please describe.**
I'm trying to read up on some of the documentation for the flow blockchain and tooling. However, there are some links that are broken and lead to 404 responses. The links that I have found so far are the following:

### Repositories:
**_Flow-SDK README.md_**
- Flow Emulator link leads to a 404 page
- multiple parties two authorizers in the TOC do not lead anywhere (not a big problem because I see it when I scroll the page).
- Read the language documentation leads to a 404 page
- Emulator.md leads to 404 page

**_Flow README.md_**
- Using the Emulator leads to a 404 page 

**Describe the solution you'd like**
FIx the links.

**Describe alternatives you've considered**
Point me in the right direction and I'll fix it myself and send a PR.

**Additional context**
N/A

**Comment by psiemens** [comment]
Thanks for pointing this out @Randy1Burrell! I'll fix up the links.
