### ISSUE TITLE
create_account err.

### ISSUE THREAD

**Issue by tinshen** [onflow/flow-go-sdk#150]
rpc error: code = InvalidArgument desc = address 9125ec0636c0b042 is invalid for chain flow-mainnet

**Comment by tinshen** [comment]
go run create_account/main.go 
err: client: rpc error: code = InvalidArgument desc = address f8d6e0586b0a20c7 is invalid for chain flow-mainnet
panic: client: rpc error: code = InvalidArgument desc = address f8d6e0586b0a20c7 is invalid for chain flow-mainnet

**Comment by tinshen** [comment]
On Flow, account creation happens inside a transaction. Because the network allows for a many-to-many relationship between public keys and accounts, it's not possible to derive a new account address from a public key offline.

**Comment by psiemens** [comment]
Hi @tinshen, were you able to solve this?

**Comment by tinshen** [comment]
> Hi @tinshen, were you able to solve this?
yes.

flow.ServiceAddress(flow.Mainnet)
