### ISSUE TITLE
Error with StartHeight, EndHeight Params for GetEventsForHeightRange function

### ISSUE THREAD

**Issue by tomsant** [onflow/flow-go-sdk#153]
### Problem

I'm using flow-go-sdk to interact with nba-smart-contracts.

I'm able to successfully establish a connection using the client and query off the top of the blockEvents, however when attempting to query for a start height less than approx the current height - 10000, the function returns "exit status 2".

### Steps to Reproduce 

```// establish connection with flow
	flowClient, err := client.New("access.mainnet.nodes.onflow.org:9000", grpc.WithInsecure())
	handleErr(err)
	ctx := context.Background()
	err = flowClient.Ping(ctx)
	handleErr(err)

	// get the latest block
	latestBlock, err := flowClient.GetLatestBlock(ctx, false)
	handleErr(err)
	fmt.Println("Current height: ", latestBlock.Height)

	currentHeight := latestBlock.Height

        blockEvents, err := flowClient.GetEventsForHeightRange(ctx, client.EventRangeQuery{
			        Type: "A.0b2a3299cc857e29.TopShot.PlayCreated",
			        StartHeight: currentHeight - 10000, // if this is > 10000 the function breaks
			        EndHeight: currentHeight,
		        })
		        if err != nil {
			        panic("Failed to query events")
		        }
```
### Acceptance Criteria

Ability to query further historical event data on flow blockchain.
  
### Context

Blocking ability to complete historical analysis on nba top shots.

**Comment by psiemens** [comment]
Hey @tomsant, I just replied to another issue with some information that might be helpful: https://github.com/onflow/flow-go-sdk/issues/154#issuecomment-784896350

You'll probably also want to limit your range queries to a few hundred blocks -- the current Access API isn't designed to handle large event queries (e.g. 10000 blocks). Sorry that isn't clear in the docs -- we're also hoping to add validation that limits queries to a practical size.

**Comment by tomsant** [comment]
@psiemens got it, appreciate the follow up! It looks like the proxy service you wrote will work for my current use case - I'll +1 the recommendation that the team explore a python sdk as well!
