### ISSUE TITLE
How to get access to archived blocks?

### ISSUE THREAD

**Issue by UCT10** [onflow/flow-go-sdk#154]
(I hope it's not a duplicate.)

I'm a data scientist (Pythonista mostly). Currently, I'm trying to figure out how to collect and process Flow blockchain data. It seems that with Access API it's only possible to get just a few hundreds of recent blocks. I want to get something about two million recent blocks. Is there any way I can do this? Should I apply for an Access node?
Also, I'm requesting for flow-python API. It would be great if you'll make one.
Thanks.

**Comment by psiemens** [comment]
Hey @UCT10, thanks for reaching out!

The protocol team is still working on a robust solution for archival data, but we hope to have it out in the coming weeks.

What kinds of queries are you interested in? If it's just events, then you might benefit from this small proxy service that I wrote: https://github.com/psiemens/flow-events-archive. 

The proxy runs on your local machine and forwards queries to the archive nodes that are maintained by our team. You can connect to the proxy in the same way you'd connect to a normal Access API. The main caveat is that it only supports `GetEventsForHeightRange` right now.

**Comment by UCT10** [comment]
@psiemens 
Great! Waiting for a similar method to be implemented in the official repo.
