### ISSUE TITLE
Retry functionality

### ISSUE THREAD

**Issue by beaugunderson** [onflow/flow-go-sdk#165]
In my own subclass of `client.Client` I've added versions of some of the methods that handle retries; they use a `WaitForConnectivity` method that I call that uses exponential backoff to wait until `Ping()` is successful.

Is something like this in-scope for the base SDK, and if so, what should the implementation look like?

(I'm unsure if this is better handled via the gRPC `Context` but I'm not sure if I quite grok how that would work yet...)

**Comment by psiemens** [comment]
I _think_ it should actually be possible to use `go-grpc-middleware/retry` with the current `client.Client`. It makes use of a client-side request interceptor.

This is adapted from the [example in their docs](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/retry):

```go
opts := []grpc_retry.CallOption{
  grpc_retry.WithBackoff(grpc_retry.BackoffExponential(100 * time.Millisecond)),
}

c, err := client.New(
  "access.mainnet.nodes.onflow.org:9000",
  grpc.WithUnaryInterceptor(grpc_retry.UnaryClientInterceptor(opts...)),
)
``` 

I'm not sure if it makes sense to bake this into `client.Client` itself, but it's definitely worthy of being in the docs.

**Comment by sideninja** [comment]
Closing in favour of https://github.com/onflow/flow-go-sdk/issues/254
