### ISSUE TITLE
Make event query more flexible

### ISSUE THREAD

**Issue by derekchiang** [onflow/flow-go-sdk#168]
Currently the `GetEventsForHeightRange` API only lets you filter for a specific type of events.

Therefore, in order to find all events from a specific contract, I currently have to either:

- Get all events in the block range and manually filter them
- Or fire multiple `GetEventsForHeightRange` calls, one for each event type from the contract.

It would be great if we could:

- Get all events from a contract
- Get all events from an account
- Get events of multiple types

**Comment by beaugunderson** [comment]
There was some recent discussion about this on Discord as well:

![image](https://user-images.githubusercontent.com/61791/110850548-c0ec8a80-8264-11eb-8a21-d5bf5e32e895.png)

![image](https://user-images.githubusercontent.com/61791/110850567-c649d500-8264-11eb-8f72-3b490c650846.png)
