### ISSUE TITLE
Topshot specific Moment Link

### ISSUE THREAD

**Issue by Jaredn** [onflow/flow-go-sdk#171]
Sorry for asking here but I'm not sure where else to ask...

In Topshot on their website there is a link to a single moment like this:

https://www.nbatopshot.com/moment/20d8cb5e-5726-4e72-a6ed-4e86006a07df

I've tried to query Flow for it but I can't seem to find that identifier anywhere.  Is this encoded on Flow somewhere?  If not, how are we expected to get it?

**Comment by beaugunderson** [comment]
The GUIDs are IDs specific to the NBATS website and aren't visible on the
chain anywhere (to my knowledge, anyway!)

**Comment by sideninja** [comment]
Please use our Discord or the forum for questions.
