### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go-sdk#172]
### Problem

I believe there is a bug [in the transaction file](https://github.com/onflow/flow-go-sdk/blob/master/docs/building-transactions.mdx) in the docs. I tried to copy-paste the content and I got the following error:
```
 --> db9f86f00981f450bbf91c9d36657e138e59fd989132f43c4a49b921b9d48f04:9:36
  |
9 |     log(greeting.concat(",").concat(guest.toString()))
  |                                     ^^^^^ not found in this scope 
```

I had to fix the transaction to:
```
...
    log(greeting.concat(",").concat(self.guest.toString()))
...
```

**Comment by turbolent** [comment]
Right, the `self.` prefix is missing, good catch!
