### ISSUE TITLE
Rate limits documentation

### ISSUE THREAD

**Issue by Dancia** [onflow/flow-go-sdk#180]
### Problem

```
/flow.access.AccessAPI/GetEventsForHeightRange rate limit reached, please retry later.
```

### Steps to Reproduce 

Spam API calls.

### Acceptance Criteria

Should report what is current rate limit for calling API or API endpoint should exist to report current rate limiting.
  
### Context

I was playing around with blockchain events processor and since API is limited some calls must be made quite often (due to limited API functionality). It is unclear how often calling API is still acceptable.

**Comment by sideninja** [comment]
Unfortunately SDK can't display this data since it's a configuration dependent on the access node. We should update our documentation to show what are rate limits. Closing in favor of https://github.com/onflow/flow/issues/840
