### ISSUE TITLE
Update usage of Google KMS API once secp256k1 keys are supported

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-go-sdk#193]
GCP recently added support for the secp256k1 elliptic curve in Google KMS.

The option is available through the console UI, but there is not yet an enum value in their API.

This PR implements a temporary workaround to allow for signing via this SDK, but we should replace it once the KMS API has first party support: https://github.com/onflow/flow-go-sdk/pull/192

**Comment by gatorbate32038** [comment]
// File: ./src/App.js import React from "react" import {AuthCluster} from "./auth-cluster" import {InitCluster} from "./init-cluster" import {ProfileCluster} from "./profile-cluster" import {useCurrentUser} from "./hooks/current-user" export default function App() { const cu = useCurrentUser() return ( <div> <AuthCluster /> <InitCluster address={cu.addr} /> <ProfileCluster address={cu.addr} /> <ProfileCluster address="0xba1132bc08f82fe2" /> <ProfileCluster address="0xf117a8efa34ffd58" /> </div> ) }

**Comment by gatorbate32038** [comment]
// File: ./src/App.js import React from "react" import {AuthCluster} from "./auth-cluster" import {InitCluster} from "./init-cluster" import {ProfileCluster} from "./profile-cluster" import {useCurrentUser} from "./hooks/current-user" export default function App() { const cu = useCurrentUser() return ( <div> <AuthCluster /> <InitCluster address={cu.addr} /> <ProfileCluster address={cu.addr} /> <ProfileCluster address="0xba1132bc08f82fe2" /> <ProfileCluster address="0xf117a8efa34ffd58" /> </div> ) }

**Comment by sideninja** [comment]
I believe this algos are not supported: https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20220112215332-a9c7c0acf9f2/googleapis/cloud/kms/v1#CryptoKeyVersion_CryptoKeyVersionAlgorithm

**Comment by sideninja** [comment]
It looks like they added the EC in enum https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/kms/v1#CryptoKeyVersion_CryptoKeyVersionAlgorithm
