### ISSUE TITLE
google kms client exporting to reuse

### ISSUE THREAD

**Issue by ytkang** [onflow/flow-go-sdk#201]
I made a commit exporting google kms client to reuse kms session.

https://github.com/ytkang/flow-go-sdk/commit/2c7dd127a6ab3076e4006c27819190118c653a6a

**Comment by psiemens** [comment]
@ytkang Can you open a PR so that we can review the change?

**Comment by ytkang** [comment]
@psiemens created with additional exporting functions
https://github.com/onflow/flow-go-sdk/pull/204
