### ISSUE TITLE
Consider exposing `languageEncodeBytesArray`

### ISSUE THREAD

**Issue by bfbachmann** [onflow/flow-go-sdk#21]
**Is your feature request related to a problem? Please describe.**
I have a custom account creation script (I am not using `examples.CreateAccount`), but I need to encode my account public key in the right format in my script. To do so I needed to essentially re-implement a function you already have in flow-go-sdk: `languageEncodeBytesArray`. 

**Describe the solution you'd like**
I figured it might be convenient for users like me if you exposed the `languageEncodeBytesArray` fucntion.

**Describe alternatives you've considered**
I just re-implemented the function myself for now, which honestly is fine.

**Additional context**
I have none, I'm afraid.

**Comment by psiemens** [comment]
Closing this because `languageEncodeBytesArray` is not longer in the `templates` package. I recommend using transaction arguments to pass byte arrays into transactions.
