### ISSUE TITLE
Toolkit for access genesis file

### ISSUE THREAD

**Issue by HarleyAppleChoi** [onflow/flow-go-sdk#212]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to query or access genesis file on go sdk. 

**Describe the solution you'd like**
A set of functions that make flowClient access to genesis file and decode that into flow types. The access on main contract such as genesis validators and delegations should also can access on genesis file.

**Describe alternatives you've considered**
Expose REST endpoint for the functionality and a guide.

**Comment by sideninja** [comment]
Hi, I might not understand your problem correctly, but how do you think is the SDK supposed to fetch the genesis file from the network? Shouldn't this first be added as an option to the AN API?

**Comment by HarleyAppleChoi** [comment]
You're right. Which repo should I move it to?

**Comment by sideninja** [comment]
I believe the https://github.com/onflow/flow-go is the correct repo for this.
