### ISSUE TITLE
Support standard PKIX, ASN.1 DER key formats

### ISSUE THREAD

**Issue by bfbachmann** [onflow/flow-go-sdk#22]
**Is your feature request related to a problem? Please describe.**
Currently users have to manually encode EC keys by appending their parameters in order to create `crypto.PublicKey`s with the SDK.

```go
pemKey :=  []byte(`-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUxHNDevkyBG2RfEZNfPr1zNtBtSD
fcrdBwjOU1VvI/p8/yUD35nm2tUaHwaFkM34kW7/ey5JuRc7qGKUhb9Esg==
-----END PUBLIC KEY-----
`)

block, _ := pem.Decode(pemKey)
if block == nil || block.Type != "PUBLIC KEY" {
    panic("Unable to decode PEM block containing public payer pub key")
}

pub, err := x509.ParsePKIXPublicKey(block.Bytes)
if err != nil {
    panic(err)
}
pubKey := pub.(*ecdsa.PublicKey)

_, err = crypto.DecodePublicKey(crypto.ECDSA_P256, append(pubKey.X.Bytes(), pubKey.Y.Bytes()...))
if err != nil {
    panic("Could not decode public payer pub key: " + err.Error())
}
```

**Describe the solution you'd like**
The SDK should support this through a similar interface to Go's `x509.ParsePKIXPublicKey`. I also ask that you make your compressed key encoding scheme clear in your godoc.

**Describe alternatives you've considered**

**Additional context**
You used to be able to pass the PKIX, ASN.1 DER encoding to `crypto.DecodePublicKey` in the old SDK, so I consider this a regression.

**Comment by psiemens** [comment]
@bfbachmann FYI, this is now implemented by `crypto.DecodePublicKeyPEM`: https://github.com/onflow/flow-go-sdk/blob/master/crypto/crypto.go#L301-L318

**Comment by bfbachmann** [comment]
That's awesome!! Thanks a ton @psiemens! ❤️
