### ISSUE TITLE
client.New reports "grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)"

### ISSUE THREAD

**Issue by zhiqiangxu** [onflow/flow-go-sdk#240]
I tried both access.mainnet.nodes.onflow.org:9000 and flow-mainnet.g.alchemy.com:443，both report the same error.

**Comment by s1119858711** [comment]
hi, have you solve this issue?

**Comment by sideninja** [comment]
This is not an issue in the Go SDK but a problem with how the library is used. Please refer to examples here to see how to set it up correctly: https://github.com/onflow/flow-go-sdk/blob/master/examples/create_account/main.go#L40
