### ISSUE TITLE
`CalculateEventsHash` logic outdated

### ISSUE THREAD

**Issue by smnzhu** [onflow/flow-go-sdk#246]
It was brought to my attention that the logic in the SDK for computing Events Hashes is out of date with the protocol logic:

SDK:
https://github.com/onflow/flow-go-sdk/blob/573abf0bffa1334267386f3960a56c65516996cc/event.go#L94-L109

Flow:
https://github.com/onflow/flow-go/blob/60b67349445b054449ccef6cbd78644ec95b20c3/model/flow/event.go#L102-L124

I believe the protocol logic changed fairly recently, and it is now generating a Merkle tree rather than directly hashing the concatenation of the events. cc @ramtinms for specific details on the changes

**Comment by ramtinms** [comment]
@sideninja I'm trying to evaluate a way to untangle this, currently talking to the team to see if we could move it to a separate package or part of the crypto lib

**Comment by sideninja** [comment]
Does the interface has to keep the signature or it can change? I'm asking because the Merkle tree root hash is returned as identifiers and it might be a good idea to keep them as identifiers since they are more defined than hash.

**Comment by sideninja** [comment]
DOD: 
- implemented
- released in new version of SDK

Current state: waiting for PR approvals cc @kerrywei

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
