### ISSUE TITLE
Transaction canonical payload problems

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go-sdk#286]
As described in an issue https://github.com/onflow/cadence/issues/1652 the transaction RLP content produced by the Go SDK differs from the one produced by the JS. This originates from the JSON encoding of the Cadence arguments, where the Go std lib encoder adds an additional newline at the end of encoded content as seen here: https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/encoding/json/stream.go;l=217
This encoded content is then used to produce the canonical payload form which differs from the one created by the JS. 

As a workaround, until canonical JSON encoding is defined in Cadence we could handle this last newline character in Go SDK and make sure to strip it.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by lmcmz** [comment]
One more:

https://github.com/onflow/cadence/issues/1652#issuecomment-1140285121

**Comment by sideninja** [comment]
@lmcmz I see. Thank you for reporting. This encoding issues will be solved in this week.
