### ISSUE TITLE
Signing payloads with a size greater than 64kb fails while using CloudKMS

### ISSUE THREAD

**Issue by pgebheim** [onflow/flow-go-sdk#317]
### Problem

When updating contracts, the whole contract source is converted to hex and then sent as part of a contract update transactions. The resulting payload that needs to be signed thus can grow larger than 64kb. This runs into issues when using CloudKMS because it has a 64kb plain text limit on its signing (and encryption/decryption) API endpoints.

The issue was introduced in the [May 5th commit](https://github.com/onflow/flow-go-sdk/commit/959016ef8960f9376fb0db87f2572cf7dcf163ef) where the data hashing was moved from being done in-memory to happening in the signer.

### Steps to Reproduce 

- Attempt to deploy a contract larger than 64kb.

### Acceptance Criteria

- Any sized contract should be deployable
  
### Context

We've worked around the issue by using the older version of flow-cli, so this is not immediately blocking.

**Comment by tarakby** [comment]
Thanks for creating the issue. 
I suggest to fix the issue by keeping the HSM hashing for data of size smaller than the limit, and pre-hashing outside the HSM for data larger than the limit. This would keep the in-HSM hashing as the default method.
