### ISSUE TITLE
Improve errors returned by Access API Client

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-go-sdk#32]
**Is your feature request related to a problem? Please describe.**

The Access API client (`client.Client`) currently wraps gRPC errors using the `%w` formatting directly. Unfortunately this strips out the gRPC status code (ref: https://github.com/grpc/grpc-go/issues/2934). 

**Describe the solution you'd like**

`Client` should return errors that can be inspected by the caller to unpack more information about the type and cause of the error.

**Describe alternatives you've considered**

We considered returning the gRPC errors directly.

**Comment by tehranifar** [comment]
Context for us needing the Status: we retry on transient errors like `DeadlineExceeded` or `Unavailable`
