### ISSUE TITLE
Provide the onceSealed() API from JS library 

### ISSUE THREAD

**Issue by vasu5235** [onflow/flow-go-sdk#321]
**Is your feature request related to a problem? Please describe.**
It takes some time for transaction to get the SEALED status on flow. As far I know, the only way to verify the transaction has been sealed is to call  `GetTransactionResult` API repeatedly

**Describe the solution you'd like**
Provide an API similar to the `onceSealed()` API in the [JS library](https://developers.flow.com/tools/fcl-js/reference/api#tx) so that user can wait for the txn to get sealed. 

**Describe alternatives you've considered**
I found this repo providing the scanning functionality based on events. Ideally, it would be nice to have this API present in the Go library as well.

**Comment by sideninja** [comment]
Callbacks are not idiomatic in Go, you can use flowkit utility library you can find as part of CLI repo, there's a function that waits for sealing https://github.com/onflow/flow-cli/blob/master/pkg/flowkit/services/transactions.go#L61
