### ISSUE TITLE
Dependency on AGPL-licensed code

### ISSUE THREAD

**Issue by phillipleblanc** [onflow/flow-go-sdk#410]
This project takes a dependency on an AGPL-licensed project (https://github.com/onflow/flow-go). This dependency was introduced with https://github.com/onflow/flow-go-sdk/pull/118 and effectively makes it impossible for any commercial projects to integrate this SDK without also agreeing to the AGPL. I'm guessing this was not intentional since this SDK is licensed as Apache 2.0.

I've [forked this project](https://github.com/spicehq/flow-go-sdk/commit/c8f1e274fcd015e8c6dac1cc202a43afaa236b68) and removed the dependency on the crypto package. However, because the `crypto` package is so fundamental to how this SDK works it reduces the usefulness. Here is an article that explains why projects (like us) don't want to link against AGPL-licensed code: https://opensource.google/documentation/reference/using/agpl-policy/.

**Comment by nvdtf** [comment]
Thanks for raising this issue. 

Flow Go SDK only uses part of onflow/flow-go/crypto so we should work on moving the needed code to remove the import.

**Comment by nvdtf** [comment]
Dependency removed here https://github.com/onflow/flow-go-sdk/pull/418
