### ISSUE TITLE
Event name factory implementation

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go-sdk#437]
We should implement a factory for event names, currently, the events are passed as strings but we should simplify the creation of the events strings by offering builder functions. 

Instead of passing an event such as: 
```
"A.7e60df042a9c0868.FlowToken"
```
We could make it as:
```
NewEvent(WithAddress(addr), WithContractName("FlowToken"), WithEventName("Withdrawal"))
```

**Comment by PratikDhanave** [comment]
hi @sideninja I like to work on this one ?

**Comment by sideninja** [comment]
@PratikDhanave awesome, go for it :)

**Comment by PratikDhanave** [comment]
@sideninja please assign this to me
