### ISSUE TITLE
Audit all endpoints for differences from protobuf

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go-sdk#736]
Review all endpoints and flag and differences in the request or response objects in the protobuf and SDK implementation.

Once we have a list, let's create issues to update all of the client handlers that should be updated.

**Comment by illia-malachyn** [comment]
**Endpoints that look fine:**

`Ping` - OK
`GetNetworkParameters` - OK
`GetTransactionsByBlockID` - OK
`GetAccount`/`GetAccountAtLatestBlock`/`GetAccountAtBlockHeight` - OK
`ExecuteScriptAtLatestBlock`/`ExecuteScriptAtBlockID`/`ExecuteScriptAtBlockHeight` - OK 
`GetLatestProtocolStateSnapshot` - OK
`GetExecutionResultForBlockID` - OK (we don't return 1 field but it's marked as deprecated)
`GetExecutionDataByBlockID` - OK
`SubscribeExecutionData` (and similar) - OK
`SubscribeEvents` (and similar) - OK


**Endpoints that return less info but look fine:**

`GetLatestBlockHeader`/`GetBlockHeaderByID`/`GetBlockHeaderByHeight`
 - we return significantly less info on the SDK side but it looks fine

`GetLatestBlock`/`GetBlockByID`/`GetBlockByHeight`
 - `GetLatestBlockRequest` request omits `full_block_response` field 
 - `BlockResponse` contains significantly less info on the SDK side but looks fine
-  `BlockHeader` & `BlockPayload` contain less info but look fine

`GetCollection` (and similar)
 - response: we don't return collection ID, but I guess we use an array index for this instead (`[]Collections`)

`GetTransaction`
 -  `block_id`, `collection_id` are not used in a request but it looks fine

`GetTransactionResult`
 - `block_id`, `collection_id` are not used in a request but it looks fine
 - `TransactionResult`has less info but looks fine
 
`GetTransactionResultByIndex`/`GetTransactionResultsByBlockID`
 - `TransactionResult` has less info but looks fine
 
 
**Endpoints that are questionable:** 

`GetNodeVersionInfo`
- we don't return `CompatibleRange compatible_range` field on the SDK side.

`SendTransaction`
 - `SendTransactionResponse` model has an ID field. We don't use it on the SDK side and return `error`. 
 
 `GetEventsForHeightRange` - OK
 - though we return 1 more field `Value cadence.Value` in `events []Events`

**Comment by nvdtf** [comment]
Given these endpoints have been in use by developers for some time, I would not prioritize any change unless explicitly asked by a developer. This being said, delivering breaking changes to make the AN API in the SDK fully equivalent seems fine too, given we have enough engineering capacity to tackle.
