### ISSUE TITLE
Update GetNodeVersionInfo response object 

### ISSUE THREAD

**Issue by illia-malachyn** [onflow/flow-go-sdk#761]
This is part of #736.

Align the response object we have in the protobuf schema with what we return in flow-go-sdk

The object we return on flow-go-sdk side:
https://github.com/onflow/flow-go-sdk/blob/master/access/grpc/grpc.go#L174

Protobuf schema:
https://github.com/onflow/flow/blob/master/protobuf/flow/entities/node_version_info.proto#L32 

Difference: 1 fields is missing.

```
// The compatible version range.
CompatibleRange compatible_range = 7;
```

**Comment by AbdullahSK03** [comment]
maybe this will help
https://bit.ly/4gx42eQ

you may need to install the c compiler
