### ISSUE TITLE
TransactionResult type differs from protobuf schema

### ISSUE THREAD

**Issue by illia-malachyn** [onflow/flow-go-sdk#769]
This is part of #736 

`TransactionResult` type on the SDK side
https://github.com/onflow/flow-go-sdk/blob/master/transaction.go#L620

`TransactionResultResponse` message in the Protobuf schema
https://github.com/onflow/flow/blob/master/protobuf/flow/access/access.proto#L416

`computation_usage` field is missing

**Comment by peterargue** [comment]
https://github.com/onflow/flow/blob/4998e288f99e963c2e6aa2474bf93c93e228a21b/protobuf/flow/access/access.proto#L416-L427

vs 

https://github.com/onflow/flow-go-sdk/blob/2689460173c00977a27b99d5a57933d260990fb1/transaction.go#L620-L628

The main difference is the SDK is missing these fields: `metadata`, `computation_usage`.

Let's go ahead and add them.

`status_code` can be ignored.
