### ISSUE TITLE
Usage of GetLatestBlockRequest might be outdated

### ISSUE THREAD

**Issue by illia-malachyn** [onflow/flow-go-sdk#770]
This is a part of #736

We don't use `full_block_response` field when querying the latest block.

Request
https://github.com/onflow/flow-go-sdk/blob/master/access/grpc/grpc.go#L245

Protobuf schema
https://github.com/onflow/flow/blob/master/protobuf/flow/access/access.proto#L324

**Comment by peterargue** [comment]
We're going to skip this work for now since ti will require a breaking change to the API and have not received any requests to add it
