### ISSUE TITLE
Make sure we use GetTransactionRequest properly 

### ISSUE THREAD

**Issue by illia-malachyn** [onflow/flow-go-sdk#771]
This is a part of #736 

`GetTransactionRequest` protobuf message was updated with new fields 
https://github.com/onflow/flow/blob/master/protobuf/flow/access/access.proto#L374

We don't use them on the SDK side
https://github.com/onflow/flow-go-sdk/blob/master/access/grpc/grpc.go#L348

**Comment by peterargue** [comment]
We're going to skip this work for now since ti will require a breaking change to the API and have not received any requests to add it
