### ISSUE TITLE
Examples need to be updated to Cadence 1.0

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-go-sdk#782]
### Problem

Some of the examples are still written in pre-Cadence 1.0 and need to be updated.

### Steps to Reproduce 

- For example, open the `verify_signature/user_signature` example
- See pre-1.0 keywords like `pub`: https://github.com/onflow/flow-go-sdk/blob/7eb6328b774496418310a8487a893c070c9e5367/examples/verify_signature/user_signature/main.go#L43
- See missing `domainSeparationTag` argument: https://github.com/onflow/flow-go-sdk/blob/7eb6328b774496418310a8487a893c070c9e5367/examples/verify_signature/user_signature/main.go#L84-L87

### Acceptance Criteria

All examples are Cadence 1.0 compatible.
  
cc @onflow/flow-develop-experience-tools

**Comment by nvdtf** [comment]
Good catch! I'll update them.
Thanks for reporting
