### ISSUE TITLE
ExecuteScriptAtLatestBlock ignores arguments on devenet

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-go-sdk#92]
### Problem

It looks like the arguments sent to scripts to devnet are beeing swallowed. 

Error message
`2020/08/29 18:52:15 Arguments [foo]
2020/08/29 18:52:16 💩 Error executing script: block output client: rpc error: code = Internal desc = failed to execute the script on the execution node: rpc error: code = Internal desc = failed to execute script: failed to execute script at block (9a4a4b1785007b2ff9d8064231033bda0f7b0cb78073aab1d7d7b377dca4970e): Execution failed:
entry point parameter count mismatch: expected 1, got 0
exit status 1`

On Emulator the same works fine.
### Steps to Reproduce 

1. check out the **devnet** branch of https://github.com/versus-flow/go-flow-tooling
2. cd to the example directory
3. `go run example.go`

The master branch has an example running against localhost.

### Acceptance Criteria

Arguments are sent to devnet

### Context

Deploying OWB project to devnet

**Comment by bjartek** [comment]
Any progress here?

**Comment by psiemens** [comment]
@bjartek I'm triaging this right now and will likely work on it later today. Thanks for reporting!

**Comment by bjartek** [comment]
Any status update on this?

**Comment by psiemens** [comment]
@bjartek Sorry, this should be resolved now. Is it still returning an error for you?

**Comment by psiemens** [comment]
This has since been resolved on devnet.
